// GENERATED by scripts/load — do not edit. Proves src/watch/watcher.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/watch/watcher.ts", async () => {
  const mod = await import("../../src/watch/watcher.js");
  expect(mod).toBeDefined();
});
