// GENERATED by scripts/load — do not edit. Proves src/hash/stable-hash.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/hash/stable-hash.ts", async () => {
  const mod = await import("../../src/hash/stable-hash.js");
  expect(mod).toBeDefined();
});
